routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'OfferController@index');


Auth::routes();
Route::get('users/suspended', 'UserController@suspended')->name('suspended');
Route::resource('users', 'UserController');
Route::any('users/reactive/{id}', 'UserController@reactive')->name('reactive');
Route::get('/home', 'OfferController@index');
Route::get('/offer', 'OfferController@index')->name('index');
Route::get('/offer/create', 'OfferController@create')->name('create');
Route::post('/offer', 'OfferController@post')->name('offer');
Route::get('/offer/{one}', 'OfferController@view');
Route::get('/log/', 'NotifyController@Log')->name('log');


Route::get('/notifications/', function () {
    // get the last 100 notifications and return it to json
    $return = [];
    $notiy = \App\Notify::take(100)->orderBy('created_at', 'desc')->get();

    foreach ($notiy as $row) {
        $offer = DB::table('offers')->where('id', $row->offer_id)->first();
        $return[$row->id]['notification_id'] = $row->id;
        $return[$row->id]['text'] = $offer->text;
        $return[$row->id]['link'] = $offer->link;
        $return[$row->id]['photo'] = $_SERVER['HTTP_HOST'] . '/photo/' . $offer->photo;
        $return[$row->id]['date'] = $row->created_at->format('Y-m-d H:i:s');
    }
    return response()->json($return);
});
Route::get('/notifications/{id}', function ($id) {
    // get the last 100 notifications and return it to json
    $return = [];
    $notiy = \App\Notify::where('id', '>', $id)->orderBy('id')->get();

    foreach ($notiy as $row) {
        $offer = DB::table('offers')->where('id', $row->offer_id)->first();
        $return[$row->id]['notification_id'] = $row->id;
        $return[$row->id]['text'] = $offer->text;
        $return[$row->id]['link'] = $offer->link;
        $return[$row->id]['photo'] = $_SERVER['HTTP_HOST'] . '/photo/' . $offer->photo;
        $return[$row->id]['date'] = $row->created_at->format('Y-m-d H:i:s');
    }
    return response()->json($return);
});
// this is the route for  resend notification
Route::post('/resend/{one}', function ($one) {
    if (\App\Notify::Notify($one)) {

        return redirect('offer')->with('status', 'Resend notification  Created!');
    }
    return redirect('offer')->with('status', 'Resend notification  Error!');
})->name('resend')
    ->middleware(['auth', 'admin']);

Route::get('/api/ios', function (Illuminate\Http\Request $request) {
    $token = $request->input('token');
    $user = $request->input('user');

    if (!is_string($token)) {
        return response()->json(['error' => sprintf(
            'Device token must be a string, "%s" given.',
            gettype($token)
        )]);
    }

    if (preg_match('/[^0-9a-fA-F]/', $token)) {
        return response()->json(['error' => sprintf(
            'Device token must be mask "%s". Token given: "%s"',
            '/[^0-9a-f]/',
            $token
        )]);
    }

    if (strlen($token) != 64) {
        return response()->json(['error' => sprintf(
            'Device token must be a 64 charsets, Token length given: %d.',
            mb_strlen($token)
        )]);
    }
    // save the token to the server
    $new_ios = App\IOS::firstOrCreate(['token' => $token,
        'user' => $user,
        'status' => '1']);
    if($new_ios->save()) {
        return response()->json(['success' => 'true']);
    }
    return response()->json(['error' => 'Faild to save Token']);

});

Route::get('/api/android', function (Illuminate\Http\Request $request) {
    $token = $request->input('token');
    $user = $request->input('user');
    if(!$token or !$user){
        return response()->json(['error' => sprintf(
            'Device token and user must be a NOT EMPTY, "%s" given.',
            gettype($token)
        )]);
    }

    // save the token to the server
    $new_ios = App\Android::firstOrCreate([
        'token' => $token,
        'user' => $user,
        'status' => '1']);
 IF ($new_ios->save()) {
      return response()->json(['success' => 'true']);
    }
    return response()->json(['error' => 'Faild to save Token']);

});

// this link will fire the send notify command
Route::get('/send/m',function (){
    //
    $affected = DB::table('notify')->where('status', '=', 1)->update(array('status' => 0));
    Artisan::call('send:notify');
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    protected $dates = ['deleted_at'];


    /**
     * Get the comments for the blog post.
     */
    public function posts()
    {
        return $this->hasMany('App\Posts');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Redirect;
use Session;
use Validator;

class UserController extends Controller
{

    /*
  * Create a new controller instance.
  *
  * @return void
  */
    public function __construct()
    {
        $this->middleware(['auth','admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = User::paginate(15);

        // list all Suspended users
        $suspend  = User::onlyTrashed()
            ->paginate(15);
        return view('users.index', ['suspend' => $suspend,'users'=>$users]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        // validate
        // read more on validation at http://laravel.com/docs/validation
        $rules = array(
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|confirmed',
            'password_confirmation' => 'required'
        );
        $validator = Validator::make($request->all(), $rules);


        if ($validator->fails()) {
            return Redirect::back()
                ->withErrors($validator)
                ->withInput($request->except('password'));
        } else {
            // create user
            $user = new User([
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password' => $request->input('password'),
            ]);
            $user->save();
            // redirect
            Session::flash('status', 'Successfully created User!');
            return Redirect::to('users');
        }


    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        // get the user
        $user = User::find($id);

        // show the edit form and pass the user
        return view('users.edit')
            ->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {

        $rules = array(
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|confirmed',
            'password_confirmation' => 'required'
        );
        $validator = Validator::make($request->all(), $rules);


        if ($validator->fails()) {
            return Redirect::back()
                ->withErrors($validator)
                ->withInput($request->except('password'));
        } else {
            // store
            $user = User::find($id);
            $user->name = $request->input('name');
            $user->email = $request->input('email');
            $user->password = $request->input('password');
            $user->save();

            Session::flash('status', 'Successfully Edited User!');
            return Redirect::to('users');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {

        // delete
        $User = User::find($id);
        $User->delete();

        // redirect
        Session::flash('status', 'Successfully Suspended  the User!');
        return Redirect::to('users');
    }

    public function suspended()
    {
        // list all Suspended users
        $users = User::onlyTrashed()
            ->paginate(15);
        return view('users.suspend', ['users' => $users]);
    }

    public function reactive($id)
    {

        if (User::withTrashed()
            ->where('id', $id)
            ->restore()) {
            Session::flash('status', 'Successfully Activated the User!');
            return Redirect::to('users');

        }
        Session::flash('error', 'Error Activate the User!');
        return Redirect::to('users/suspended');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create User</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('users.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                <label for="password" class="col-md-4 control-label">Password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control" name="password" required>

                                    @if ($errors->has('password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Create
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit {{$user->name}}</div>
                    <div class="panel-body">
                        <!-- if there are creation errors, they will show here -->
                        {{ Html::ul($errors->all()) }}


                        {{ Form::model($user, array('route' => array('users.update', $user->id), 'method' => 'PUT')) }}

                        <div class="form-group">
                            {{ Form::label('name', 'Name') }}
                            {{ Form::text('name', null, array('class' => 'form-control')) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('password', 'Password') }}
                            {{ Form::text('password', null, array('class' => 'form-control')) }}
                        </div>
                        <div class="form-group">
                            <label for="password-confirm" class="">Confirm Password</label>
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" >
                        </div>
                        <div class="form-group">
                            {{ Form::label('email', 'Email') }}
                            {{ Form::email('email', null, array('class' => 'form-control')) }}
                        </div>



                        {{ Form::submit('Edit the User!', array('class' => 'btn btn-primary')) }}

                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Users</div>

                    <div class="panel-body">
                        @if(count($users)>0)
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>E-mail</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>
                                            {{$user->name}}
                                        </td>
                                        <td>
                                            {{$user->email}}
                                        </td>
                                        <td>

                                            <a href="{{route('users.edit',[$user->id])}}"><span
                                                        class="label label-success">Edit</span></a>
                                            @if($user->email!=env('ADMIN_MAIL','NOTHING'))
                                                {{ Form::open(array('url' => 'users/' . $user->id, 'class' => 'pull-right')) }}
                                                {{ Form::hidden('_method', 'DELETE') }}
                                                {{ Form::submit('Suspend', array('class' => 'btn btn-danger')) }}
                                                {{ Form::close() }}
                                            @endif()

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        @else
                            <p>Create your first <a href="{{Route('create')}}">offer</a></p>
                        @endif
                        {!! $users->render() !!}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Suspended Users :</div>

                    <div class="panel-body">
                        @if(count($suspend)>0)
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>E-mail</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($suspend as $user)
                                    <tr>
                                        <td>
                                            {{$user->name}}
                                        </td>
                                        <td>
                                            {{$user->email}}
                                        </td>
                                        <td>
                                            {{ Form::open(array('url' => 'users/reactive/' . $user->id, 'class' => 'pull-right')) }}
                                            {{ Form::hidden('_method', 'POST') }}
                                            {{ Form::submit('Reactive', array('class' => 'btn btn-info')) }}
                                            {{ Form::close() }}

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        @else
                            <p>Your Suspension List Is empty </p>
                        @endif
                        {!! $suspend->render() !!}
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Offer {{$offer->id}}</div>

                    <div class="panel-body">
                        <p> Text : {{$offer->text}}</p>
                        <p>Url : {{$offer->link}}</p>
                        <hr/>
                        <img src="{{URL::to('/')}}/photo/{{$offer->photo}}" class="img-rounded" width="100%">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/suspend.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Users</div>

                    <div class="panel-body">
                        @if(count($users)>0)
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>E-mail</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>
                                            {{$user->name}}
                                        </td>
                                        <td>
                                            {{$user->email}}
                                        </td>
                                        <td>
                                            {{ Form::open(array('url' => 'users/reactive/' . $user->id, 'class' => 'pull-right')) }}
                                            {{ Form::hidden('_method', 'POST') }}
                                            {{ Form::submit('Reactive', array('class' => 'btn btn-info')) }}
                                            {{ Form::close() }}

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                        @else
                            <p>Your Suspension List Is empty </p>
                        @endif
                        {!! $users->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection