routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'OfferController@index');


Auth::routes();
Route::get('users/suspended', 'UserController@suspended')->name('suspended');
Route::resource('users', 'UserController');
Route::any('users/reactive/{id}', 'UserController@reactive')->name('reactive');
Route::get('/home', 'OfferController@index');
Route::get('/offer', 'OfferController@index')->name('index');
Route::get('/offer/create', 'OfferController@create')->name('create');
Route::post('/offer', 'OfferController@post')->name('offer');
Route::get('/offer/{one}', 'OfferController@view');
Route::get('/log/', 'NotifyController@Log')->name('log');


Route::get('/notifications/', function () {
    // get the last 100 notifications and return it to json
    $return = [];
    $notiy = \App\Notify::take(100)->orderBy('created_at', 'desc')->get();

    foreach ($notiy as $row) {
        $offer = DB::table('offers')->where('id', $row->offer_id)->first();
        $return[$row->id]['notification_id'] = $row->id;
        $return[$row->id]['text'] = $offer->text;
        $return[$row->id]['link'] = $offer->link;
        $return[$row->id]['photo'] = $_SERVER['HTTP_HOST'] . '/photo/' . $offer->photo;
        $return[$row->id]['date'] = $row->created_at->format('Y-m-d H:i:s');
    }
    return response()->json($return);
});
Route::get('/notifications/{id}', function ($id) {
    // get the last 100 notifications and return it to json
    $return = [];
    $notiy = \App\Notify::where('id', '>', $id)->orderBy('id')->get();

    foreach ($notiy as $row) {
        $offer = DB::table('offers')->where('id', $row->offer_id)->first();
        $return[$row->id]['notification_id'] = $row->id;
        $return[$row->id]['text'] = $offer->text;
        $return[$row->id]['link'] = $offer->link;
        $return[$row->id]['photo'] = $_SERVER['HTTP_HOST'] . '/photo/' . $offer->photo;
        $return[$row->id]['date'] = $row->created_at->format('Y-m-d H:i:s');
    }
    return response()->json($return);
});
// this is the route for  resend notification
Route::post('/resend/{one}', function ($one) {
    if (\App\Notify::Notify($one)) {

        return redirect('offer')->with('status', 'Resend notification  Created!');
    }
    return redirect('offer')->with('status', 'Resend notification  Error!');
})->name('resend')
    ->middleware(['auth', 'admin']);

Route::get('/api/ios', function (Illuminate\Http\Request $request) {
    $token = $request->input('token');
    $user = $request->input('user');

    if (!is_string($token)) {
        return response()->json(['error' => sprintf(
            'Device token must be a string, "%s" given.',
            gettype($token)
        )]);
    }

    if (preg_match('/[^0-9a-fA-F]/', $token)) {
        return response()->json(['error' => sprintf(
            'Device token must be mask "%s". Token given: "%s"',
            '/[^0-9a-f]/',
            $token
        )]);
    }

    if (strlen($token) != 64) {
        return response()->json(['error' => sprintf(
            'Device token must be a 64 charsets, Token length given: %d.',
            mb_strlen($token)
        )]);
    }
    // save the token to the server
    $new_ios = App\IOS::firstOrCreate(['token' => $token,
        'user' => $user,
        'status' => '1']);
    if($new_ios->save()) {
        return response()->json(['success' => 'true']);
    }
    return response()->json(['error' => 'Faild to save Token']);

});

Route::get('/api/android', function (Illuminate\Http\Request $request) {
    $token = $request->input('token');
    $user = $request->input('user');
    if(!$token or !$user){
        return response()->json(['error' => sprintf(
            'Device token and user must be a NOT EMPTY, "%s" given.',
            gettype($token)
        )]);
    }

    // save the token to the server
    $new_ios = App\Android::firstOrCreate([
        'token' => $token,
        'user' => $user,
        'status' => '1']);
 IF ($new_ios->save()) {
      return response()->json(['success' => 'true']);
    }
    return response()->json(['error' => 'Faild to save Token']);

});

// this link will fire the send notify command
Route::get('/send/m',function (){
    //
    $affected = DB::table('notify')->where('status', '=', 1)->update(array('status' => 0));
    Artisan::call('send:notify');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->

                <a class="navbar-brand" href="{{ url('/') }}" style="
    margin: 0;
    padding: 0;
" >
                    <img src="{{url('/')}}/logo.png" width="80" height="50" title=" {{ config('app.name', 'Laravel') }}">
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                @if (!Auth::guest())
                    <ul class="nav navbar-nav">
                        &nbsp;
                        <li><a href="{{route('index')}}">Offers</a></li>
                        &nbsp;
                        <li><a href="{{route('create')}}">Create Offer</a></li>
                        &nbsp;
                        <li><a href="{{route('users.index')}}">Mange Users</a></li>
                        <li><a href="{{route('users.create')}}">Create User</a></li>
                        <li><a href="{{route('log')}}">Logs </a></li>

                    </ul>
            @endif
            <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>

                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    @if (session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif
    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
</body>
</html>